name: Just lepture
author: Hsiaoming Yang
description: "Love its people, but never trust its government. Believe in evolution rather than revolution."
baseurl: "http://lepture.com"
permalink: "/:dirname/:filename"
timezone: Asia/Chongqing

per_page: 10
paginator_style: "page/:num"

excludes: ["Makefile", "_config.yml"]

links:
  - name: About
    url: /resume
  - name: Chinese
    url: /zh/
  - name: English
    url: /en/

social:
  - name: Email
    url: "mailto:me@lepture.com"
  - name: Twitter
    url: "https://twitter.com/lepture"
  - name: Weibo
    url: "http://weibo.com/lepture"
  - name: GitHub
    url: "https://github.com/lepture"
  - name: Feed
    url: "http://feeds.lepture.com/lepture"

disqus: lepture
google_analytics: "UA-21475122-1"
